// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2_pMR5tD-SsZApk2ssdOaJxvhaVGASS0',
    appId: '1:570364000751:android:7bb73daed1ce7031d99e1a',
    messagingSenderId: '570364000751',
    projectId: 'contactform-chapsmart',
    databaseURL: 'https://contactform-chapsmart-default-rtdb.firebaseio.com',
    storageBucket: 'contactform-chapsmart.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBo6n9-483nCkAp7K66uRyTpmgxR84AuC4',
    appId: '1:570364000751:ios:6e0244e3033c1835d99e1a',
    messagingSenderId: '570364000751',
    projectId: 'contactform-chapsmart',
    databaseURL: 'https://contactform-chapsmart-default-rtdb.firebaseio.com',
    storageBucket: 'contactform-chapsmart.firebasestorage.app',
    iosBundleId: 'tz.co.chapsmart.app',
  );

}